do_you_want_to_continue=ต้องการดำเนินการต่อหรือไม่? ({{y/n}}):

catfood_warning=<@w>คำเตือน: การแก้ไขอาหารแมวอาจทำให้ถูกแบนได้ ใช้โดยยอมรับความเสี่ยงด้วยตัวเอง</>\n{{do_you_want_to_continue}}
legend_ticket_warning=<@w>คำเตือน: การแก้ไขตั๋วตำนานอาจทำให้ถูกแบนได้ ใช้โดยยอมรับความเสี่ยงด้วยตัวเอง</>\n{{do_you_want_to_continue}}
rare_ticket_warning=
><@w>คำเตือน: การแก้ไขตั๋วหายากอาจทำให้ถูกแบนได้ ใช้โดยยอมรับความเสี่ยงด้วยตัวเอง</>
>คุณสามารถใช้ฟีเจอร์แลกตั๋วหายากเพื่อรับตั๋วหายากด้วยความเสี่ยงถูกแบนที่น้อยกว่า
platinum_ticket_warning=
><@w>คำเตือน: การแก้ไขตั๋วแพลทินัมอาจทำให้ถูกแบนได้ ใช้โดยยอมรับความเสี่ยงด้วยตัวเอง</>
>คุณสามารถใช้ฟีเจอร์เศษแพลทินัมเพื่อรับตั๋วแพลทินัมด้วยความเสี่ยงถูกแบนที่น้อยกว่า

select_an_option_to_continue=เลือกตัวเลือกเพื่อดำเนินการแก้ไข {feature_name} ต่อ:

continue_editing=แก้ไข {feature_name} ต่อ
go_to_safe_feature=ไปที่ฟีเจอร์ {safer_feature_name} ที่ปลอดภัยกว่า
cancel_editing=ยกเลิกการแก้ไข {feature_name}

rare_ticket_trade_enter=กรอกจำนวนตั๋วหายากที่ต้องการ<@q>เพิ่ม</> (ค่าสูงสุด: <@q>{max}</>) (จำนวนปัจจุบัน: <@q>{current}</>):
rare_ticket_trade_storage_full=<@e>ข้อผิดพลาด: พื้นที่คลังแมวของคุณไม่พอ กรุณาเว้นพื้นที่ว่างไว้ 1 ช่อง!</>
rare_ticket_successfully_traded=
><@su>ให้ตั๋วหายาก {rare_ticket_count} ใบสำเร็จแล้ว</>
>ตอนนี้คุณต้องเข้าคลังแมวแล้วกดปุ่ม <@q>Use all</> จากนั้นกดปุ่ม <@q>Trade for Ticket</> เพื่อรับตั๋วของคุณ

rare_tickets_l=ตั๋วหายาก
rare_ticket_trade_l=แลกตั๋วหายาก

rare_ticket_trade_maxed=<@e>ข้อผิดพลาด: คุณมีตั๋วหายากสูงสุดอยู่แล้ว!\nกรุณาใช้ก่อนที่จะทำสิ่งนี้!</>

platinum_tickets_l=ตั๋วแพลทินัม
platinum_shards_l=เศษแพลทินัม
