total_selected_enemies=เลือกศัตรูอยู่ <@t>{total}</> ตัว
unlock_enemy_guide_success=<@su>ปลดล็อกรายการสารานุกรมศัตรูสำเร็จแล้ว</>
remove_enemy_guide_success=<@su>ลบรายการสารานุกรมศัตรูสำเร็จแล้ว</>
selected_enemy=เลือก <@t>{name}</> (<@t>{id}</>) แล้ว
select_enemies_valid=เลือกศัตรูทั้งหมดที่อยู่ในสารานุกรมศัตรู
select_enemies_invalid=เลือกศัตรูทั้งหมดที่ไม่อยู่ในสารานุกรมศัตรู
select_enemies_all=เลือกศัตรูทั้งหมด
select_enemies_id=เลือกศัตรูตาม ID
select_enemies_name=เลือกศัตรูตามชื่อ
select_enemies=เลือกศัตรู:
enter_enemy_ids=คุณสามารถดู ID ศัตรูได้ที่นี่: <@t>https://battlecats.miraheze.org/wiki/Enemy_Release_Order</>\nกรอก ID ศัตรู {{range_input}}:
enter_enemy_name=กรอกชื่อศัตรู:
enemy_not_found_name=<@w>ไม่พบศัตรูที่ชื่อ <@s>{name}</></>
unlock_enemy_guide=ปลดล็อกรายการสารานุกรมศัตรู
remove_enemy_guide=ลบรายการสารานุกรมศัตรู
enemy_guide=สารานุกรมศัตรู
edit_enemy_guide=กรอกตัวเลือกเพื่อแก้ไขรายการสารานุกรมศัตรู:
