fix_gamatoto_crash=แก้ไขปัญหา gamatoto ทำให้เกมขัดข้อง
fix_time_errors=แก้ไขปัญหาเกี่ยวกับเวลา

fix_ototo_crash=แก้ไขปัญหา ototo ทำให้เกมขัดข้อง

fix_gamatoto_crash_success=<@su>แก้ไขปัญหา gamatoto ทำให้เกมขัดข้องสำเร็จแล้ว</>
fix_time_errors_success=<@su>แก้ไขปัญหาเกี่ยวกับเวลาสำเร็จแล้ว <@w>(เวลาของอุปกรณ์ทั้งสองเครื่องต้องถูกต้องจึงจะได้ผล)</></>
fix_ototo_crash_success=<@su>แก้ไขปัญหา ototo ทำให้เกมขัดข้องสำเร็จแล้ว</>

fixes=แก้ไขปัญหา

unlock_equip_menu=ปลดล็อกเมนูอุปกรณ์
equip_menu_unlocked=<@su>ปลดล็อกเมนูอุปกรณ์สำเร็จแล้ว</>
