enter_raw_gamatoto_xp=กรอกค่า XP ดิบของ Gamatoto
enter_gamatoto_level=กรอกเลเวล Gamatoto
edit_gamatoto_level_q=กรอกตัวเลือกเพื่อแก้ไขเลเวล gamatoto:
gamatoto_xp=XP ของ Gamatoto
gamatoto_level=เลเวล Gamatoto
gamatoto_level_success=<@su>ตั้งเลเวล gamatoto เป็น <@s>{level}</> สำเร็จแล้ว (XP: <@s>{xp}</>)</>
gamatoto_level_current=<@t>เลเวล gamatoto ปัจจุบันคือ <@q>{level}</> (XP: <@q>{xp}</>)</>
gamatoto_xp_level=XP / เลเวล ของ Gamatoto

current_gamatoto_helpers=ผู้ช่วยปัจจุบัน:
gamatoto_helper=ผู้ช่วย: <@t>{name}</> (ระดับความหายาก: <@t>{rarity_name}</>)

new_gamatoto_helpers=ผู้ช่วยใหม่:
gamatoto_helpers=ผู้ช่วย Gamatoto

ototo_cat_cannon=ปืนใหญ่แมว Ototo

current_cannon_stats=สถานะปืนใหญ่ปัจจุบัน:

cannon_part=<@t><@q>{name}</>{buffer}(เลเวล <@s>{level}</>)</>
development={buffer}(การพัฒนา: <@q>{development}</>)
cannon_stats={parts}

foundation=ฐาน
style=สไตล์
effect=เอฟเฟกต์
improved_foundation=ฐานที่พัฒนาแล้ว
improved_style=สไตล์ที่พัฒนาแล้ว

unknown_stage=ไม่ทราบขั้น (<@s>{stage}</>)

selected_cannon=<@t>ปืนใหญ่ที่เลือก: <@q>{name}</></>
selected_cannon_stage=<@t>ปืนใหญ่: <@q>{name}</> ขั้นปัจจุบัน: <@q>{stage}</></>

cannon_edit_type=ต้องการแก้ไขปืนใหญ่แต่ละกระบอกทีละกระบอก หรือใช้การแก้ไขกับปืนใหญ่ที่เลือกทั้งหมดพร้อมกัน?:

cannon_dev_level_q=ต้องการแก้ไขการพัฒนาของปืนใหญ่ หรือเลเวลของปืนใหญ่?:
development_o=การพัฒนา
level_o=เลเวล

select_development=เลือกขั้นการพัฒนา:
select_cannon=เลือกปืนใหญ่
cannon_level=เลเวลปืนใหญ่

cannon_success=<@su>แก้ไขปืนใหญ่ ototo สำเร็จแล้ว</>

cat_shrine=แก้ไขศาลเจ้าแมว
shrine_level=แก้ไขเลเวลศาลเจ้า
shrine_xp=XP ของศาลเจ้า
current_shrine_xp_level=<@t>XP ปัจจุบัน: <@q>{xp}</> (เลเวล: <@q>{level}</>)</>
cat_shrine_choice_dialog=คุณต้องการทำอะไร?:
shrine_level_dialog=กรอกเลเวลศาลเจ้าแมว (สูงสุด: <@q>{max_level}</>):
shrine_xp_dialog=กรอก XP ศาลเจ้าแมว (สูงสุด: <@q>{max_xp}</>):
cat_shrine_edited=<@su>แก้ไขศาลเจ้าแมวสำเร็จแล้ว</>
make_catshrine_appear=แสดงศาลเจ้าแมวในเกม
make_catshrine_disappear=ซ่อนศาลเจ้าแมวในเกม
