event_tickets=ตั๋วอีเวนต์ / ตั๋วนำโชค
downloading_gatya_data=กำลังดาวน์โหลดข้อมูลอีเวนต์กาชา...
download_gatya_data_success=<@su>ดาวน์โหลดข้อมูลอีเวนต์กาชาสำเร็จแล้ว</>
download_gatya_data_fail=<@e>ดาวน์โหลดข้อมูลอีเวนต์กาชาไม่สำเร็จ ลองใหม่อีกครั้ง</>
save_gatya_error=<@e>บันทึกข้อมูลกาชาไม่สำเร็จ เนื่องจาก {error}</>
gatya_by_id_q=ต้องการเลือกแบนเนอร์กาชาด้วย <@t>ID</> หรือ <@t>ชื่อ?</>:
by_id=ด้วย ID
by_name=ด้วยชื่อ
