gold_pass_dialog=กรอก <@t>officer id</> ที่ต้องการ (เว้น<@q>ว่าง</>ไว้เพื่อรับ id <@q>แบบสุ่ม</> หรือกรอก <@q>-1</> เพื่อ<@q>ลบ</> gold pass):
gold_pass=Gold Pass / Officer Club
gold_pass_remove_success=<@su>ลบ gold pass สำเร็จแล้ว</>
gold_pass_get_success=<@su>ได้รับ gold pass สำเร็จแล้ว (id: <@t>{id}</>)</>. <@w>หมายเหตุ: เกมอาจลบ gold pass ของคุณหากตรวจพบว่าคุณไม่ได้มีจริง ปัญหานี้ผมไม่สามารถแก้ไขได้ กรุณาอย่าแจ้งบั๊กเกี่ยวกับเรื่องนี้</>
officer_pass_fixed=<@su>แก้ไขปัญหา officer club ขัดข้องสำเร็จแล้ว</>
fix_officer_pass_crash=แก้ไข Officer Club ขัดข้อง
