# หมายเหตุ: ไม่ใช่ไอเทมทั้งหมดที่อยู่ในไฟล์นี้

catamins=คาทามิน
catfruit=ผลไม้แมว
base_materials=วัสดุฐานทัพ
inquiry_code=Inquiry Code
rare_gatya_seed=เมล็ดกาชาหายาก
normal_gatya_seed=เมล็ดกาชาปกติ
event_gatya_seed=เมล็ดกาชาอีเวนต์
unlocked_slots=ช่องที่ปลดล็อก|ช่องอุปกรณ์|ทีมที่ตั้งไว้
password_refresh_token=Password Refresh Token
challenge_score=คะแนนท้าทาย
dojo_score=คะแนนโดโจ
items=ไอเทม
user_rank_rewards=รับรางวัล User Rank (ไม่ได้ให้รางวัลจริง)

catfood=อาหารแมว
xp=XP
normal_tickets=ตั๋วธรรมดา|ตั๋วพื้นฐาน|ตั๋วเงิน
rare_tickets=ตั๋วหายาก|ตั๋วทอง
platinum_tickets=ตั๋วแพลทินัม
legend_tickets=ตั๋วตำนาน
100_million_tickets=ตั๋วครบรอบ 100 ล้านดาวน์โหลด
100_million_warn=<@w>หมายเหตุ: คุณจะเห็นและใช้ตั๋วนี้ได้ก็ต่อเมื่ออีเวนต์ 100 Million Downloads กำลังเปิดใช้งานอยู่เท่านั้น</>
platinum_shards=เศษแพลทินัม
np=NP
leadership=ความเป็นผู้นำ
catseyes=ดวงตาแมว
battle_items=ไอเทมต่อสู้
duration=<@t>{days}</t> วัน, <@t>{hours}</t> ชั่วโมง, <@t>{minutes}</> นาที, <@t>{seconds}</> วินาที
endless_item_item=<@s>{item}</> : <@s>{int}</>
endless_items_success=<@su>แก้ไขไอเทมไม่จำกัดสำเร็จแล้ว</>
invalid_minute_count=<@e>จำนวนนาทีไม่ถูกต้อง</>
enter_duration_minutes=กรอกระยะเวลาเป็นนาทีที่ไอเทมไม่จำกัดจะใช้ได้ (หากกรอก <@t>infinity</> ไอเทมจะใช้ได้ตลอดไป):
infinity_duration=<@t>infinity</>
infinity=ไม่จำกัด
enter_duration_minutes_item=กรอกระยะเวลาเป็นนาทีที่ <@t>{item}</> ไม่จำกัดจะใช้ได้ (หากกรอก <@t>infinity</> ไอเทมจะใช้ได้ตลอดไป):
battle_items_endless=ไอเทมต่อสู้ไม่จำกัด
talent_orbs=ลูกแก้วพรสวรรค์
scheme_items=ไอเทมกิจกรรม
labyrinth_medals=เหรียญเขาวงกต
restart_pack=แพ็กเริ่มใหม่|โหมด Returner
engineers=วิศวกร
gamototo=Gamatoto / Ototo
special_skills=ความสามารถพิเศษ / ความสามารถพื้นฐาน
treasure_chests=หีบสมบัติ
unknown_treasure_chest_name=ไม่ทราบชื่อหีบสมบัติ ({id})

rare_ticket_trade=แลกตั๋วหายาก
rare_ticket_trade_feature_name=แลกตั๋วหายาก (ได้ตั๋วหายากแบบไม่ถูกแบน)

other=อื่นๆ
gatya=กาชา
levels=เลเวล / เนื้อเรื่อง / สมบัติ
cats_special_skills=แมว / ความสามารถพิเศษ

gatya_item_unknown_name=ไอเทมที่ไม่ทราบชื่อ
unknown_catamin_name=ไม่ทราบชื่อคาทามิน <@t>{id}</>
unknown_catseye_name=ไม่ทราบชื่อดวงตาแมว <@t>{id}</>
unknown_catfruit_name=ไม่ทราบชื่อผลไม้แมว <@t>{id}</>
unknown_labyrinth_medal_name=ไม่ทราบชื่อเหรียญเขาวงกต <@t>{id}</>

reset_golden_cat_cpus_success=<@su>รีเซ็ตจำนวนครั้งการใช้ CPU แมวทองสำเร็จแล้ว</>
reset_golden_cat_cpus=รีเซ็ตจำนวนครั้งการใช้ CPU แมวทอง
edit_endless_q=ต้องการแก้ไขไอเทมไม่จำกัดแต่ละอัน<@t>ทีละอัน</> หรือ<@t>ทั้งหมดพร้อมกัน</>?:
