tutorial_already_cleared=<@w>คุณผ่าน tutorial แล้ว</>
tutorial_cleared=<@su>ผ่าน tutorial สำเร็จแล้ว</>
clear_tutorial=ผ่าน Tutorial

clear_stages=ผ่านด่าน
unclear_stages=ยกเลิกผ่านด่าน
clear_unclear_q=ต้องการ <@t>ผ่านด่าน</> หรือ <@t>ยกเลิกผ่านด่าน</>?:

add_enigma_stages=เพิ่มด่าน Enigma
clear_enigma_stages=ล้างด่าน Enigma
current_enigma_stages=ด่าน Enigma ปัจจุบัน:
enigma_stage=ด่าน Enigma <@q>{name}</> (id: <@q>{id}</>) 
unknown_enigma_name=ไม่ทราบชื่อ Enigma (id: <@q>{id}</>)
enigma_select=เลือกด่าน Enigma ที่จะเพิ่ม
enigma_success=<@su>เพิ่มด่าน Enigma สำเร็จแล้ว</>
wipe_enigma=ต้องการล้างด่าน Enigma ปัจจุบันหรือไม่? ({{y/n}}):
aku_realm_unlocked=<@su>ปลดล็อกอาณาจักรอาคุสำเร็จแล้ว</>
unlock_aku_realm=ปลดล็อกอาณาจักรอาคุ

select_story_chapters=เลือกบทของเนื้อเรื่อง:
chapter_progress_txt=(เช่น <@q>0</> = ยังไม่ผ่านด่านใดเลย, <@q>1</> = ผ่านด่านแรก, <@q>2</> = ผ่านด่านแรกและด่านที่สอง, ... <@q>{max}</> = ผ่านทุกด่าน)
edit_chapter_progress_all=กรอกความคืบหน้าที่จะตั้งให้แต่ละบท {{chapter_progress_txt}}:
edit_chapter_progress=กรอกความคืบหน้าที่จะตั้งให้ <@t>{chapter_name}</> {{chapter_progress_txt}}:
edit_stage_clear_count=กรอกจำนวนครั้งที่ผ่านด่าน:
story_cleared=<@su>ผ่านเนื้อเรื่องสำเร็จแล้ว</>
individual_chapters=แต่ละบท
all_chapters=ทุกบท
individual_chapters_dialog=ต้องการแก้ไขความคืบหน้าของแต่ละบท<@t>ทีละบท</> หรือตั้งให้<@t>ทุกบท</>มีความคืบหน้าเท่ากัน?:
individual_clear_counts=จำนวนครั้งที่ผ่านแยกรายด่าน
all_clear_counts=จำนวนครั้งที่ผ่านทั้งหมด
individual_clear_counts_dialog=ต้องการแก้ไขจำนวนครั้งที่ผ่านของแต่ละด่าน<@t>ทีละด่าน</> หรือตั้งให้<@t>ทุกด่าน</>มีจำนวนครั้งที่ผ่านเท่ากัน?:
clear_story=บทหลักของเนื้อเรื่อง|ผ่านเนื้อเรื่อง

map_name_star={name} มงกุฎ {star}

clear=ผ่านด่าน
unclear=ยกเลิกผ่านด่าน

outbreaks=ด่านซอมบี้ระบาด

clear_unclear_outbreaks=ต้องการ <@t>ผ่านด่าน</> หรือ <@t>ยกเลิกผ่านด่าน</> ซอมบี้ระบาด?:
clear_outbreaks_success=<@su>ผ่านด่านซอมบี้ระบาดสำเร็จแล้ว</>
unclear_outbreaks_success=<@su>ยกเลิกผ่านด่านซอมบี้ระบาดสำเร็จแล้ว</>
no_valid_outbreaks=<@e>ข้อผิดพลาด: ไม่พบด่านซอมบี้ระบาดที่ถูกต้อง</>

aku_chapters=บทอาณาจักรอาคุ
aku_clear_success=<@su>ผ่านอาณาจักรอาคุสำเร็จแล้ว</>
aku_current_stage=ด่านอาณาจักรอาคุ <@q>{name}</> (id: <@q>{id}</>)

itf_timed_scores=คะแนนจับเวลา Into the Future
itf_timed_scores_dialog=ต้องการแก้ไขคะแนนจับเวลาแบบ<@t>ทั้งบทพร้อมกัน</> หรือ<@t>รายด่าน</>?:
itf_timed_scores_edited=<@su>แก้ไขคะแนนจับเวลา Into The Future สำเร็จแล้ว</>
itf_timed_score_dialog=กรอกคะแนนจับเวลา (สามารถระบุเป็นช่วงได้ เช่น <@t>6000</>-<@t>9000</> เพื่อสุ่มคะแนน):
current_stage={chapter_name} <@t>{stage_name}</>
itf_timed_scores_individual_dialog=ต้องการแก้ไขคะแนนจับเวลาของแต่ละด่านที่เลือก<@t>ทีละด่าน</> หรือตั้งให้ด่านที่เลือก<@t>ทั้งหมด</>มีคะแนนเท่ากัน?:

filibuster_stage_reclearing_allowed=<@su>เปิดใช้งานด่าน Filibuster ใหม่สำเร็จแล้ว</>
filibuster_reclearing=เปิดใช้งานด่าน Filibuster ใหม่

all_selected_stages=ด่านที่เลือกทั้งหมด

unknown_map_name=ไม่ทราบชื่อแมพ (id: <@q>{id}</>)
map_name={name} <@s>(id: <@q>{id}</>)</>
edit_map_chapters=เลือกบท

clear_whole_chapters=ผ่านทั้งบท
unclear_whole_chapters=ยกเลิกผ่านทั้งบท

clear_specific_stages=ผ่านด่านที่กำหนด
unclear_specific_stages=ยกเลิกผ่านด่านที่กำหนด

select_clear_type=ต้องการ <@t>ผ่านทั้งบท</> หรือ <@t>ผ่านด่านที่กำหนด</>?:
select_unclear_type=ต้องการ <@t>ยกเลิกผ่านทั้งบท</> หรือ <@t>ยกเลิกผ่านด่านที่กำหนด</>?:

custom_star_count_per_chapter_yn=ต้องการตั้งจำนวนดาว/มงกุฎเองสำหรับแต่ละบทหรือไม่? ({{y/n}}):
modify_clear_amounts=กำลังตั้งจำนวนครั้งที่ผ่านเป็น <@t>1</> สำหรับด่านที่เลือกแต่ละด่าน ต้องการเปลี่ยนหรือไม่? ({{y/n}}):
clear_amount_chapter=ตั้งจำนวนครั้งที่ผ่านแยกกันสำหรับแต่ละบทที่เลือก
clear_amount_all=ตั้งจำนวนครั้งที่ผ่านเท่ากันสำหรับทุกบทที่เลือก
clear_amount_stages=ตั้งจำนวนครั้งที่ผ่านแยกกันสำหรับแต่ละด่านที่เลือก
select_clear_amount_type=เลือกรูปแบบการตั้งจำนวนครั้งที่ผ่านที่ต้องการใช้:
clear_amount_enter=กรอกจำนวนครั้งที่ผ่าน:
custom_star_count_per_chapter=กรอกจำนวนดาว/มงกุฎ (สูงสุด <@q>{max}</>):

custom_star_count_per_chapter_unclear=
>กรอกดาว/มงกุฎที่ต้องการลบ:
><@s><@t>1</> = ยกเลิกผ่านทั้งแมพ</>
><@s><@t>2</> = ยกเลิกผ่านแมพมงกุฎ/ดาวที่ 2, 3 และ 4</>
><@s><@t>3</> = ยกเลิกผ่านแมพมงกุฎ/ดาวที่ 3 และ 4</>
><@s><@t>4</> = ยกเลิกผ่านแมพมงกุฎ/ดาวที่ 4</>
>(สูงสุด <@q>{max}</>):

current_sol_chapter=บท <@t>{name}</> (id: <@q>{id}</>)
current_sol_star=ดาว/มงกุฎ: <@q>{star}</>
current_sol_stage=ด่าน <@q>{name}</> (id: <@q>{id}</>)
map_chapters_edited=<@su>แก้ไขบทสำเร็จแล้ว</>
sol=Stories of Legend
event=ด่านอีเวนต์ปกติ
collab=ด่านอีเวนต์คอลแล็บ
select_map=เลือกแมพ
select_map_dialog=
>เลือกแมพที่ต้องการแก้ไข
>คุณสามารถกรอกช่วงตัวเลข (เช่น <@q>1-5</>) ตัวเลขเดี่ยว (เช่น <@q>1 3 5</>) หรือทั้งสองแบบรวมกัน (เช่น <@q>1-3 5</>)
>คุณยังสามารถกรอกชื่อ/บางส่วนของชื่อแมพ (เช่น <@t>{example}</>) เพื่อค้นหา/เลือกได้
>คุณยังสามารถกรอกคำว่า <@q>all</> เพื่อเลือกทุกบท
>กรอก:
no_map_found=<@e>ไม่พบแมพที่ชื่อ <@s>{name}</></>
finished_selecting_maps=เลือกแมพเสร็จแล้วหรือยัง? ({{y/n}}):
current_maps=แมพปัจจุบัน:

select_stage=เลือกด่าน

gauntlets=Gauntlets
collab_gauntlets=Gauntlets คอลแล็บ
uncanny=Uncanny Legends
catamin_stages=ด่าน Catamin
behemoth_culling=Behemoth Culling
legend_quest=Legend Quest
towers=หอคอย
zero_legends=Zero Legends

unclear_other_stages=ต้องการเขียนทับความคืบหน้าปัจจุบันในบทนี้หรือไม่? ({{y/n}}) <@t>n</> = เปลี่ยนแค่จำนวนครั้งที่ผ่านของด่านที่เลือก, <@t>y</> = ยกเลิกผ่านด่านหลังๆ ในบทที่เคยผ่านไปแล้ว:

select_stage_progress=กรอกด่านที่ต้องการผ่านจนถึง (รวมด่านนั้นด้วย):

zero_legends_warning=<@w>คำเตือน: หากเวอร์ชันเกมของคุณไม่มีแมพ zero legends เกมจะขัดข้องหากคุณพยายามแก้ไขให้ผ่าน!</>

stages_select=กรอกตัวเลข {{range_input}}

change_clear_amount_catamin=เปลี่ยนจำนวนครั้งที่ผ่านของบท
clear_unclear_stage_catamin=ผ่าน / ยกเลิกผ่านด่าน Catamin
catamin_stage_clear_q=ต้องการ <@t>เปลี่ยนจำนวนครั้งที่ผ่านบท catamin</> หรือแค่ <@t>ผ่านหรือยกเลิกผ่านด่าน</>?:

select_map_from_names=เลือกแมพ

enter_clear_amount_catamin_map=กรอกจำนวนครั้งที่ผ่านที่จะตั้งให้บท <@t>{name}</> (ID: <@t>{id}</t>) (<@t>0</> = ยังไม่เคยผ่านบทนี้, <@t>3</> ขึ้นไปหมายถึงบทนี้จะหายไป):
enter_clear_amount_catamin=กรอกจำนวนครั้งที่ผ่านที่จะตั้งให้บทที่เลือก (<@t>0</> = ยังไม่เคยผ่านบทนี้, <@t>3</> ขึ้นไปหมายถึงบทนี้จะหายไป):

catamin_stage_success=<@su>แก้ไขด่าน catamin สำเร็จแล้ว</>

catamin_clear_amounts_q=ต้องการแก้ไขจำนวนครั้งที่ผ่านของแต่ละบท<@t>ทีละบท</> หรือ<@t>ทั้งหมดพร้อมกัน</>?:

dojo_catclaw_championships=ผ่าน Dojo Catclaw Championships

finished=เสร็จสิ้น
edit_chapters_q=คุณต้องการแก้ไขอะไร?:

clear_whole_chapter=ผ่านทั้งบท
clear_to_specific_stage=ผ่านจนถึงด่านที่กำหนด
clear_whole_q=ต้องการ <@t>ผ่านทั้งบทในครั้งเดียว</> หรือ <@t>ผ่านจนถึงด่านที่กำหนดในบทนั้น</>?:

clear_all=ผ่านทุกบท
handle_individually=แก้ไขแต่ละบททีละบท

clear_chapters_q=ต้องการ <@t>ผ่านทุกบทที่เลือก</> หรือ <@t>แก้ไขความคืบหน้าของแต่ละบททีละบท</>?:
max_stars=กรอกจำนวนมงกุฎสูงสุด (สูงสุด: <@t>{max}</>):

edit_map_all=จำนวนครั้งที่ผ่านเท่ากันสำหรับทุกบท
edit_chapters_q_all=ต้องการตั้ง <@t>จำนวนครั้งที่ผ่านเท่ากันสำหรับทุกบทที่เลือก</> หรือแก้ไขจำนวนครั้งที่ผ่านของ<@t>แต่ละบททีละบท</>?:

edit_whole_chapter=ตั้งจำนวนครั้งที่ผ่านเท่ากันสำหรับทั้งบท
edit_specific_stages=แก้ไขจำนวนครั้งที่ผ่านของด่านที่กำหนด
edit_chapter_q=ต้องการ <@t>ตั้งจำนวนครั้งที่ผ่านเท่ากันสำหรับทุกด่านในบท</> หรือ <@t>แก้ไขจำนวนครั้งที่ผ่านสำหรับด่านที่กำหนด</>?:

each_stage_individually=ตั้งจำนวนครั้งที่ผ่านแยกกันสำหรับแต่ละด่านที่เลือก
stage_all_at_once=ตั้งจำนวนครั้งที่ผ่านเท่ากันสำหรับด่านที่เลือกทั้งหมด
set_clear_count_stage_q=ต้องการ <@t>ตั้งจำนวนครั้งที่ผ่านแยกกันสำหรับแต่ละด่านที่เลือก</> หรือ <@t>ตั้งจำนวนครั้งที่ผ่านเท่ากันสำหรับด่านที่เลือกทั้งหมด</>?:

unknown_stage_name=ไม่ทราบชื่อด่าน (index: <@t>{index}</>)
current_stage_map=<@t>{name} <@s>(index: <@q>{index}</>)</></>

edit_progress_clear=แก้ไขความคืบหน้าแมพ
edit_progress_unclear=แก้ไขความคืบหน้าแมพ (รองรับการยกเลิกผ่าน)
edit_clear_counts=แก้ไขจำนวนครั้งที่ผ่านด่าน

keep_selecting=เลือกต่อ
remove_selection=ลบตัวเลือก
finish_selection=เสร็จสิ้นการเลือก
map_selection_q=คุณต้องการทำอะไร?:
