medals=เหรียญเหมียว
add_medals=เพิ่มเหรียญ
remove_medals=ลบเหรียญ
medal_add_remove_dialog=ต้องการ <@t>เพิ่มเหรียญ</> หรือ <@t>ลบเหรียญ</>?:
medal_string={medal_name}: <@q>{medal_req}</>
select_medals=เลือกเหรียญ:
medals_added=<@su>เพิ่มเหรียญเหมียวสำเร็จแล้ว</>
medals_removed=<@su>ลบเหรียญเหมียวสำเร็จแล้ว</>
