missions=ภารกิจแคทนิป / มิชชั่น|มิชชั่นแมว
complete_reward=ผ่านมิชชั่นโดยไม่รับรางวัล
complete_claim=ผ่านมิชชั่นและรับรางวัล
uncomplete=ยกเลิกผ่านมิชชั่น
select_mission_claim=ต้องการ <@t>ผ่านมิชชั่นโดยไม่รับรางวัล</> หรือ <@t>ผ่านมิชชั่นและรับรางวัล <@q>(ไม่ได้ให้รางวัลจริง)</></> หรือ <@t>ยกเลิกผ่านมิชชั่นถ้าทำได้</>?:
select_missions=เลือกมิชชั่นที่จะแก้ไข:
missions_edited=<@su>แก้ไขมิชชั่นสำเร็จแล้ว</>
