playtime_str=<@t>{hours}</> $(hours: !=1($hours)$, ชั่วโมง)/$ <@t>{minutes}</> $(minutes: !=1($minutes)$, นาที)/$ <@t>{seconds}</> $(seconds: !=1($seconds)$, วินาที)/$ (<@t>{frames} </>$(frames: !=1($frames)$, เฟรม)/$)
playtime_current=เวลาเล่นปัจจุบัน: {{playtime_str}}
playtime_edited=แก้ไขเวลาเล่นเป็น {{playtime_str}} สำเร็จแล้ว
playtime_hours_prompt=กรอกจำนวน<@t>ชั่วโมง</>ที่ต้องการตั้งเป็นเวลาเล่น:
playtime_minutes_prompt=กรอกจำนวน<@t>นาที</>ที่ต้องการตั้งเป็นเวลาเล่น:
playtime_seconds_prompt=กรอกจำนวน<@t>วินาที</>ที่ต้องการตั้งเป็นเวลาเล่น:
playtime=เวลาเล่น
