scheme_items_edit_success=<@su>แก้ไขไอเทมกิจกรรมสำเร็จแล้ว</>
scheme_items_select_gain=เลือกไอเทมกิจกรรมที่ต้องการได้รับ
scheme_items_select_remove=เลือกไอเทมกิจกรรมที่ต้องการลบ
gain_remove_scheme_items=ต้องการ <@t>รับ</> หรือ <@t>ลบ</> ไอเทมกิจกรรม?:
gain_scheme_items=รับไอเทมกิจกรรม
remove_scheme_items=ลบไอเทมกิจกรรม
