special_skills_dialog=เลือกความสามารถพื้นฐานที่ต้องการอัปเกรด
upgrade_individual_skill=กรอกระดับอัปเกรดสำหรับสกิลที่เลือกแต่ละอัน
upgrade_all_skills=กรอกระดับอัปเกรดที่จะใช้กับสกิลที่เลือกทั้งหมด

upgrade_skills_select_mod=เลือกตัวเลือกเพื่ออัปเกรดสกิล:

selected_skill=เลือก <@t>{name}</> แล้ว
selected_skill_upgrades={{selected_skill}}: <@t>{base_level}<@s>+</>{plus_level}</>
selected_skill_upgraded=อัปเกรด <@t>{name}</> เป็น <@t>{base_level}<@s>+</>{plus_level} แล้ว
skills_edited=<@su>แก้ไขความสามารถพิเศษสำเร็จแล้ว</>
