total_current_orbs=จำนวนลูกแก้วทั้งหมดในปัจจุบัน: <@q>{total_orbs}</>
total_current_orb_types=จำนวนชนิดลูกแก้วทั้งหมดในปัจจุบัน: <@q>{total_types}</>
current_orbs=ลูกแก้วปัจจุบัน:
orb_select=เลือกลูกแก้วพรสวรรค์ที่จะแก้ไข:
selected_orbs=ลูกแก้วพรสวรรค์ที่เลือก:
edit_orbs_individually=ต้องการแก้ไขลูกแก้วแต่ละอันทีละอัน (<@q>1</>) หรือทั้งหมดพร้อมกัน (<@q>2</>)?:
edit_orbs_all=กรอกค่าที่จะแก้ไขให้ลูกแก้วที่เลือกทั้งหมด (สูงสุด <@t>{max}</>):
failed_to_load_orbs=โหลดลูกแก้วพรสวรรค์ไม่สำเร็จ

edit_orbs_help=
>ช่วยเหลือ:
>เกรดที่มี: {all_grades_str}
>คุณสมบัติที่มี: {all_attributes_str}
>ผลที่มี: {all_effects_str}
><@w>หมายเหตุ: ไม่ใช่ทุกเกรดและทุกผลที่จะมีในทุกคุณสมบัติ</>
>ตัวอย่างการกรอก:
>    <c>aku</> - เลือกลูกแก้ว <c>aku ทั้งหมด</>
>    <r>red</> <b>s</> - เลือกลูกแก้ว<r>สีแดงทั้งหมด</>ที่มีเกรด <b>s</>
>    <b>alien</> <r>d</> <r>0</> - เลือกลูกแก้ว <b>alien</> เกรด <r>d</> ที่เพิ่ม<r>พลังโจมตี</>
>    <o>c</> <dm>1</> - เลือกลูกแก้วเพิ่มพลัง stories of legend เกรด <o>c</>
>หากต้องการเลือก<@q>ทั้งหมด</> ให้กรอก:
>    <@q>*</>
>หากต้องการ<@q>เลือกหลายรายการ</> ให้คั่นด้วย<@q>เครื่องหมายจุลภาค</>แบบนี้:
>    <b>s</> <bl>black</> <g>4</>,<r>d</> <o>3</>,<g>floating</>
>

