whole_chapters=ทั้งบท
individual_stages=รายด่าน
treasure_groups=กลุ่ม/ชุดสมบัติ
treasure_dialog=ต้องการแก้ไขสมบัติแบบ <@t>ทั้งบทพร้อมกัน</>, <@t>รายด่าน</> หรือ<@t>กลุ่มสมบัติ</>รายกลุ่ม?:
treasures_edited=<@su>แก้ไขสมบัติสำเร็จแล้ว</>
per_chapter=ต่อบท
all_selected_chapters=ทุกบทที่เลือก
edit_per_chapter=ต้องการแก้ไขข้อมูลสำหรับ <@t>ทุกบทที่เลือก</> หรือ <@t>แต่ละบททีละบท</>?:
no_treasure=ไม่มีสมบัติ
custom_treasure_level=ระดับสมบัติกำหนดเอง (<@w>แก้ไขเฉพาะเมื่อคุณเข้าใจว่ากำลังทำอะไรอยู่เท่านั้น!</>)
treasure_level_dialog=กรอกระดับสมบัติที่ต้องการตั้ง:
custom_treasure_level_dialog=กรอกระดับสมบัติกำหนดเองที่ต้องการตั้ง:
select_stage_by_id=เลือกด่านตาม ID
select_stage_by_name=เลือกด่านตามชื่อ
select_stage_dialog=ต้องการเลือกด่านตาม <@t>ID</> หรือ <@t>ชื่อ</>?:
select_stage_id=กรอก ID ด่านที่ต้องการเลือก {{range_input}}
select_stages_name=เลือกด่าน:
select_treasure_groups=เลือกกลุ่มสมบัติที่ต้องการแก้ไข:
story_treasures=สมบัติเนื้อเรื่อง
current_chapter=บทปัจจุบัน: <@t>{chapter_name}</>
current_treasure_group=กลุ่มสมบัติปัจจุบัน: <@t>{treasure_group_name}</>
group_individual=แยกรายกลุ่ม
group_all_at_once=ทุกกลุ่มที่เลือก
select_treasure_groups_individual=ต้องการแก้ไขระดับสมบัติของแต่ละ<@t>กลุ่มสมบัติ</>ทีละกลุ่ม หรือ<@t>ทุกกลุ่มที่เลือก</>พร้อมกัน?:
