claim=รับรางวัล
unclaim=ยกเลิกรับรางวัล
fix_claimed=แก้ไขสถานะรับรางวัล
claim_or_unclaim_ur=ต้องการ <@t>รับรางวัล</> หรือ <@t>ยกเลิกรับรางวัล</> หรือ <@t>แก้ไขสถานะรับรางวัล (ยกเลิกการรับรางวัลที่สูงกว่า user rank ปัจจุบัน)</> ของรางวัล user rank?:
select_ur=เลือกรางวัล user rank
ur_claimed_success=<@su>รับรางวัล user rank สำเร็จแล้ว</>
ur_unclaimed_success=<@su>ยกเลิกรับรางวัล user rank สำเร็จแล้ว</>
ur_string=แรงค์: <@s>{rank}</>: {description}
ur_fix_claimed_success=<@su>แก้ไขสถานะรับรางวัล user rank สำเร็จแล้ว</>
