config=ตั้งค่า
edit_config=แก้ไขการตั้งค่า
default_value=(ค่าเริ่มต้น: <@q>{default_value}</>)
current_value=(ค่าปัจจุบัน: <@q>{current_value}</>)
config_value_txt=<@s>{{current_value}} {{default_value}}</>

config_dialog=เลือกตัวเลือกการตั้งค่าที่ต้องการแก้ไข:

update_to_beta_desc=ตรวจสอบอัปเดตเวอร์ชันเบต้า {{config_value_txt}}
update_to_beta=อัปเดตเป็นเวอร์ชันเบต้า

config_full=<@t>{key_desc}</>

disable_maxes_desc=ปิดค่าสูงสุดเมื่อทำการแก้ไข {{config_value_txt}}
disable_maxes=ปิดค่าสูงสุด

max_backups_desc=จำนวนไฟล์สำรองของไฟล์เซฟสูงสุดที่จะเก็บไว้ {{config_value_txt}}
max_backups=จำนวนไฟล์สำรองสูงสุด

available_themes=ธีมที่มี:
theme_desc=ธีมที่จะใช้ {{config_value_txt}}
theme=ธีม

show_missing_locale_keys=แสดงคีย์ locale ที่ขาดหายไป
show_missing_locale_keys_desc=แสดงคีย์ locale ทั้งหมดที่มีใน locale ภาษาอังกฤษ แต่ไม่มีใน locale ปัจจุบัน มีประโยชน์สำหรับการดีบัก: {{config_value_txt}}

reset_cat_data_desc=รีเซ็ตข้อมูลแมวทั้งหมดเมื่อทำการลบแมวออกจากไฟล์เซฟ {{config_value_txt}}
reset_cat_data=รีเซ็ตข้อมูลแมวเมื่อลบแมว

filter_current_cats_desc=เมื่อเลือกแมวเพื่อแก้ไข ให้กรองแมวที่ไม่มีในไฟล์เซฟออก {{config_value_txt}}
filter_current_cats=กรองเฉพาะแมวปัจจุบันตอนเลือกแมว

set_cat_current_forms_desc=เมื่อ true form แมว ให้ตั้งฟอร์มปัจจุบันของแมวเป็นฟอร์มที่เพิ่งปลดล็อก {{config_value_txt}}
set_cat_current_forms=ตั้งฟอร์มปัจจุบันของแมวเมื่อปลดล็อกฟอร์ม

strict_upgrade_desc=เมื่ออัปเกรดแมว ให้ตรวจสอบสิ่งต่างๆ เช่น user rank และความคืบหน้าของเกม เพื่อให้อัปเกรดแมวได้ถึงระดับที่กำหนดเท่านั้น {{config_value_txt}}
strict_upgrade=ตรวจสอบการอัปเกรดแบบเข้มงวด

separate_cat_edit_options_desc=แยกตัวเลือกการแก้ไขแมวออกเป็นหลายฟีเจอร์ {{config_value_txt}}
separate_cat_edit_options=แยกตัวเลือกการแก้ไขแมว

strict_ban_prevention_desc=เมื่อทำสิ่งที่เกี่ยวข้องกับเซิร์ฟเวอร์ ให้สร้างบัญชีใหม่เพื่อลดโอกาสถูกแบน {{config_value_txt}}
strict_ban_prevention=การป้องกันแบนขั้นเข้ม

max_request_timeout_desc=เวลาสูงสุดที่จะรอให้คำขอเสร็จสิ้น (วินาที) {{config_value_txt}}
max_request_timeout=เวลาหมดเวลาคำขอสูงสุด

game_data_repo_desc=Repository ที่จะใช้สำหรับข้อมูลเกม {{config_value_txt}}
game_data_repo=Repository ข้อมูลเกม
game_data_repo_dialog=กรอก repository ข้อมูลเกมที่ต้องการใช้:

force_lang_game_data_desc=บังคับให้โปรแกรมใช้ข้อมูลเกมของ locale ปัจจุบัน แม้ว่าไฟล์เซฟจะเป็นเวอร์ชันอื่น {{config_value_txt}}
force_lang_game_data=บังคับใช้ข้อมูลเกมของ locale ปัจจุบัน

clear_tutorial_on_load_desc=ล้างข้อมูล tutorial เมื่อโหลดไฟล์เซฟเข้าโปรแกรม {{config_value_txt}}
clear_tutorial_on_load=ล้าง tutorial เมื่อโหลดเซฟ

remove_ban_message_on_load_desc=ลบข้อความแจ้งแบนเมื่อโหลดไฟล์เซฟเข้าโปรแกรม {{config_value_txt}}
remove_ban_message_on_load=ลบข้อความแจ้งแบนเมื่อโหลดเซฟ

unlock_cat_on_edit_desc=ปลดล็อกแมวเมื่อคุณแก้ไขเลเวล พรสวรรค์ ฟอร์ม ฯลฯ {{config_value_txt}}
unlock_cat_on_edit=ปลดล็อกแมวเมื่อแก้ไข

use_file_dialog_desc=ใช้หน้าต่างเลือกไฟล์ของ tkinter แทนการกรอกที่อยู่ไฟล์ {{config_value_txt}}
use_file_dialog=ใช้หน้าต่างเลือกไฟล์

adb_path_desc=ที่อยู่ของไฟล์ adb {{config_value_txt}}
adb_path=ที่อยู่ ADB

use_pkexec_waydroid=ใช้ pkexec ในการรันคำสั่ง waydroid
use_pkexec_waydroid_desc=การรัน <@s>waydroid shell</> ต้องใช้สิทธิ์ root ใช้ <@s>pkexec</> เพื่อหลีกเลี่ยงการรันโปรแกรมทั้งหมดด้วยสิทธิ์ root {{config_value_txt}}

ignore_parse_error_desc=ข้ามข้อผิดพลาดในการอ่านไฟล์และข้ามการอ่านข้อมูลเซฟที่เหลือ <@w>คำเตือน: ทำเช่นนี้เฉพาะกรณีที่ไฟล์เซฟเสียหายเท่านั้น ควรแจ้งปัญหาการอ่านไฟล์ทุกกรณีในดิสคอร์ด</> {{config_value_txt}}
ignore_parse_error=ข้ามข้อผิดพลาดในการอ่านไฟล์เซฟ

string_config_dialog=กรอกค่าใหม่สำหรับ <@q>{val}</>:


enable_disable_dialog=ต้องการ <@q>เปิดใช้งาน</> หรือ <@q>ปิดใช้งาน</> ฟีเจอร์นี้?:


enable=เปิดใช้งาน
disable=ปิดใช้งาน

enabled=เปิดใช้งานอยู่
disabled=ปิดใช้งานอยู่

config_success=<@su>อัปเดตการตั้งค่าสำเร็จแล้ว</>

yaml_create_error=<@e>ไม่สามารถสร้างไฟล์ yaml ที่ <@s>{path}<@s> ได้ ปัญหานี้มักเกิดจากสิทธิ์การเข้าถึงในเครื่องของคุณ ลองรันโปรแกรมด้วยสิทธิ์ root/Administrator ดู:
