another_path=กรอกที่อยู่ไฟล์ด้วยตนเอง
select_files_dir=เลือกไฟล์ในไดเรกทอรี:
enter_path=กรอกที่อยู่/ตำแหน่งไฟล์:
enter_path_dir=กรอกที่อยู่/ตำแหน่งโฟลเดอร์:
enter_path_default=กรอกที่อยู่/ตำแหน่งไฟล์ (ค่าเริ่มต้น: <@t>{default}</>):
current_files_dir=ไฟล์ปัจจุบันในไดเรกทอรี <@t>{dir}</>:
other_dir=กรอกไดเรกทอรีอื่น
no_files_dir=<@e>ไม่มีไฟล์ในไดเรกทอรี</>
path_not_exists=<@e>ไม่พบที่อยู่นี้</>
