input_int=กรอกตัวเลขระหว่าง <@q>{min}</> ถึง <@q>{max}</>:
select_edit=เลือกตัวเลือกสำหรับ <@t>{group_name}</>:
input_int_default=กรอกตัวเลขระหว่าง <@q>{min}</> ถึง <@q>{max}</> (ค่าเริ่มต้น <@q>{default}</>):
input_many=กรอกตัวเลขระหว่าง <@q>{min}</> ถึง <@q>{max}</> คั่นด้วยเว้นวรรค:
input_single=กรอกตัวเลขระหว่าง <@q>{min}</> ถึง <@q>{max}</>:
input=กรอกค่าสำหรับ <@t>{name}</> (ค่าปัจจุบัน: <@q>{value}</>) (ค่าสูงสุด: <@q>{max}</>):
input_min=กรอกค่าสำหรับ <@t>{name}</> (ค่าปัจจุบัน: <@q>{value}</>) (ช่วง: <@q>{min}</> - <@q>{max}</>):
input_non_max=กรอกค่าสำหรับ <@t>{name}</> (ค่าปัจจุบัน: <@q>{value}</>):
value={name} : <@q>{value}</>
input_generic=กรอกค่าสำหรับ <@t>{name}</> (ค่าสูงสุด: <@q>{max}</>):
input_all=กรอกค่าสำหรับ <@t>{name}</> ทั้งหมด (ค่าสูงสุด: <@q>{max}</>):
value_changed=<@su>เปลี่ยน <@s>{name}</> เป็น <@s>{value}</> สำเร็จแล้ว
individual_or_all_at_once=ต้องการแก้ไข <@t>{group}</> แบบ <@t>ทีละรายการ</> หรือ <@t>ทั้งหมดพร้อมกัน</>?:
value_gave=<@su>ให้ <@s>{name}</> สำเร็จแล้ว
all_at_once=เลือกทุกตัวเลือกพร้อมกัน
invalid_input=<@e>ข้อมูลที่กรอกไม่ถูกต้อง กรุณาลองใหม่อีกครั้ง</>
input_no_max=กรอกตัวเลขสำหรับ <@t>{name}</> ค่าปัจจุบัน: <@t>{value}</>:
invalid_input_int=<@e>ข้อมูลที่กรอกไม่ถูกต้อง กรุณากรอกตัวเลขระหว่าง <@s>{min}</> ถึง <@s>{max}</></>
invalid_range=<@e>รูปแบบช่วงไม่ถูกต้อง ต้องเป็น \<เลข\>-\<เลข\> หรือ \<เลข\> ไม่ใช่ {val}</e>
select_option=เลือกตัวเลือก:
finish=เสร็จสิ้น
features=ฟีเจอร์:
go_back=ย้อนกลับ
yes_key=y
quit_key=q
range_input=คั่นด้วยเว้นวรรค (เช่น <@t>1 2 3 192</>) หรือกรอกเป็นช่วง (เช่น <@t>1-43</>) หรือกรอก <@t>all</>:
select_features=
>เลือกฟีเจอร์โดยกรอก
>- <@q>ตัวเลข</> ที่ตรงกับตัวเลขด้านซ้าย
>- <@t>ข้อความ</> เพื่อค้นหาฟีเจอร์
>คุณสามารถกด <@t>enter</> เพื่อดูฟีเจอร์ทั้งหมด
>ฟีเจอร์บางอย่างเป็น <@t>หมวดหมู่</> เมื่อเลือกจะแสดง <@t>ฟีเจอร์ย่อย</> ทั้งหมด
>กรอก:

individual=ทีละรายการ
individually=ทีละรายการ
edit_all_at_once=ทั้งหมดพร้อมกัน
