# เอกสารฉบับเต็ม: https://codeberg.org/fieryhenry/ExampleEditorLocale#format-of-the-properties-files
# การใส่สีข้อความ
#
# <@p> = สีหลัก (primary)
# <@s> = สีรอง (secondary)
# <@t> = สีที่สาม (tertiary)
# <@q> = สีที่สี่ (quaternary)
# <@e> = สีข้อผิดพลาด (error)
# <@w> = สีคำเตือน (warning)
# <@su> = สีสำเร็จ (success)
#
# </> = ปิดสีปัจจุบัน
# เมื่อใส่สี ให้ใช้แท็กด้านบน ไม่ใช่รหัสสี/ชื่อสีจริง เพื่อให้ใช้ได้กับหลายธีม
# ใช้รหัสสี/ชื่อสีจริงเฉพาะตอนที่สีนั้นมีความหมายสำคัญ เช่น การให้สีลูกแก้วพรสวรรค์เป้าหมายเป็นสีแดง
# หากต้องการพิมพ์ < หรือ > หรือ / ในข้อความ ให้ใส่ \ นำหน้า เช่น \< หรือ \> หรือ \/
#
# <#rrggbb> = สีจากรหัสเฮกซ์
#
# <w> = ขาว
# <bl> = ดำ
# <r> = แดง
# <g> = เขียว
# <b> = น้ำเงิน
# <y> = เหลือง
# <m> = ม่วงแดง
# <c> = ฟ้า
# <dy> = เหลืองเข้ม
# <dg> = เทาเข้ม
# <db> = น้ำเงินเข้ม
# <dc> = ฟ้าเข้ม
# <dm> = ม่วงแดงเข้ม
# <dr> = แดงเข้ม
# <dgn> = เขียวเข้ม
# <lg> = เทาอ่อน
# <o> = ส้ม

downloading=<@su>กำลังดาวน์โหลด <@s>{file_name}</> จาก <@s>{pack_name}</> เวอร์ชัน <@s>{version}</> รหัสประเทศ <@s>{country_code}</>
failed_to_download_game_data=<@e>ดาวน์โหลดข้อมูลเกม <@s>{file_name}</> จาก <@s>{pack_name}</> เวอร์ชัน <@s>{version}</> รหัสประเทศ <@s>{country_code}</> ไม่สำเร็จ ลิงก์: <@s>{url}</s> ลองตรวจสอบการเชื่อมต่ออินเทอร์เน็ตของคุณ</>
failed_to_get_game_versions=<@e>ไม่สามารถดึงข้อมูลเวอร์ชันเกมได้ ลองตรวจสอบการเชื่อมต่ออินเทอร์เน็ตของคุณ</>
no_device_error=<@e>ไม่พบอุปกรณ์ที่เชื่อมต่ออยู่</>
no_package_name_error=<@e>ไม่พบแพ็กเกจ Battle Cats อุปกรณ์ของคุณอาจยังไม่ได้ root หรือคุณอาจต้องลองใหม่และตรวจสอบว่าได้เปิดเข้าฐานแมวอย่างน้อยหนึ่งครั้งแล้ว</>
exit=ออก
tkinter_not_found=<@e>ไม่พบ tkinter หากคุณไม่ได้ใช้งานบนมือถือ กรุณาติดตั้งแล้วลองใหม่อีกครั้ง</>
tkinter_not_found_enter_path_file=กรุณากรอกที่อยู่/ตำแหน่งของไฟล์ {initialfile}:
tkinter_not_found_enter_path_file_save=กรุณากรอกที่อยู่/ตำแหน่งที่จะบันทึกไฟล์ {initialfile}:
tkinter_not_found_enter_path_dir=กรุณากรอกที่อยู่/ตำแหน่งของโฟลเดอร์ {initialdir} แทน:
discord_url=https://discord.gg/DvmMgvn5ZB

welcome=
><@t>ยินดีต้อนรับสู่ <@s>Battle Cats Save File Editor</>!
>สร้างโดย <@s>fieryhenry</>
>
>Codeberg: <@s>https://codeberg.org/fieryhenry/BCSFE-Python</>
>Discord: <@s>{{discord_url}}</> - กรุณาแจ้งบั๊กที่ <@s>#bug-reports</> และข้อเสนอแนะที่ <@s>#suggestions</>
>บริจาค: <@s>https://ko-fi.com/fieryhenry</>
>
>ตำแหน่งไฟล์ตั้งค่า: <@s>{config_path}</>
>
>{theme_text}
>
>{locale_text}
>
><@q>ขอขอบคุณ:
>- <@s>Lethal's editor</> ที่เป็นแรงบันดาลใจและช่วยให้ผมคิดวิธีแพตช์ไฟล์เซฟและแก้ไข cf/xp ในตอนแรก: <@s>https://www.reddit.com/r/BattleCatsCheats/comments/djehhn/editoren/</>
>- โค้ดของ <@s>Beeven</> และ <@s>csehydrogen</> ที่ช่วยให้ผมเข้าใจวิธีแพตช์ไฟล์เซฟ: https://github.com/beeven/battlecats และ https://github.com/csehydrogen/BattleCatsHacker
>- ทุกคนที่สนับสนุนผลงานของผม เป็นแรงผลักดันให้ทำโปรเจกต์นี้และโปรเจกต์อื่นๆ ต่อไป: <@s>https://ko-fi.com/fieryhenry</>
>- ทุกคนในดิสคอร์ดที่ให้เซฟ แจ้งบั๊ก เสนอฟีเจอร์ใหม่ๆ และเป็นคอมมูนิตี้ที่ยอดเยี่ยม: <@s>{{discord_url}}</></>
>
><@w>หากคุณจ่ายเงินเพื่อโปรแกรมนี้ แสดงว่าคุณถูกหลอก โปรแกรมนี้ฟรีและเป็นโอเพนซอร์ส</>
>
><@w>ใช้เครื่องมือนี้โดยยอมรับความเสี่ยงด้วยตัวเอง ผมไม่รับผิดชอบต่อการถูกแบนหรือความเสียหายใดๆ ที่เกิดกับไฟล์เซฟของคุณ
>แน่นอนว่า save editor พยายามป้องกันไม่ให้เกิดเหตุการณ์เหล่านี้ แต่ผมไม่สามารถรับประกันได้ว่าเซฟของคุณจะปลอดภัย 100%
>หากเซฟของคุณเสียหาย ก็ยังขอให้แจ้งในดิสคอร์ดด้วย
>แนะนำให้สำรองไฟล์เซฟไว้ก่อนแก้ไขทุกครั้ง</>

report_message=กรุณาแจ้งที่ <@s>#bug-reports</> บนดิสคอร์ด: <@s>{{discord_url}}</>
report_message_l=กรุณาแจ้งที่ <@s>#bug-reports</> บนดิสคอร์ด: <@s>{{discord_url}}</>
try_again_message=กรุณาลองใหม่อีกครั้ง หากยังพบข้อผิดพลาดอยู่ {{report_message_l}}</>
all=ทั้งหมด

error=<@e>เกิดข้อผิดพลาด (<@s>{error}</>, เวอร์ชันโปรแกรม: <@s>{version}</>) {{report_message_l}}\n{traceback}
see_log=<@e>กรุณาดูรายละเอียดเพิ่มเติมในไฟล์ log</>
max=สูงสุด
none=ไม่มี
unknown=ไม่ทราบ

leave=\n<@q>ขอบคุณที่ใช้งาน Battle Cats Save File Editor!</>
checking_for_changes=<@t>กำลังตรวจสอบการเปลี่ยนแปลง...</>
no_changes=<@su>ไม่พบการเปลี่ยนแปลง</>
changes_found=<@su>พบการเปลี่ยนแปลง</>

y/n=y/n
yes=yes

git_not_installed=<@e>ไม่ได้ติดตั้ง Git กรุณาติดตั้ง เพิ่มลงใน PATH แล้วลองใหม่อีกครั้ง</>
failed_to_get_repo=<@e>ไม่สามารถดึงข้อมูล repo: "<@t>{url}</>" อาจไม่มีอยู่จริง หรือคุณไม่มีการเชื่อมต่ออินเทอร์เน็ต</>
failed_to_run_git_cmd=<@e>ไม่สามารถรันคำสั่ง git: "<@t>{cmd}</>" ลองตรวจสอบการเชื่อมต่ออินเทอร์เน็ตของคุณ</>
cancel=ยกเลิก

update_external=ตรวจสอบการอัปเดต
updating_external_content=<@q>กำลังอัปเดตข้อมูลภายนอก...</>

downloading_map_names=<@q>กำลังดึงชื่อแมพ... (โค้ด: <@t>{code}</>) อาจใช้เวลาสักครู่...</>

select_device=เลือกอุปกรณ์:

continue_q=ดำเนินการต่อหรือไม่? ({{y/n}}):

no_data_version=<@e>ไม่พบข้อมูลเวอร์ชันเกมล่าสุด อาจเกิดจากปัญหาอินเทอร์เน็ต กรุณาลองใหม่อีกครั้ง</>

no_feature_with_name=<@e>ไม่พบฟีเจอร์ที่ชื่อ: <@s>{name}</></>

checking_bcsfe_update=<@q>กำลังตรวจสอบอัปเดตของ <@t>{app_name}</>...</>
no_update_required=<@q>ไม่มีอัปเดตสำหรับ <@t>{app_name}</></>
