save_load_option=เลือกตัวเลือกเพื่อโหลดไฟล์เซฟ:
download_save=ดาวน์โหลดไฟล์เซฟด้วยรหัสถ่ายโอนและรหัสยืนยัน
select_save_file=เลือกไฟล์เซฟจากไฟล์
adb_pull_save=ดึงไฟล์เซฟจากอุปกรณ์ด้วย adb
load_save_data_json=โหลดข้อมูลเซฟจาก json
root_storage_pull_save=ดึงไฟล์เซฟจาก root storage
save_save_dialog=บันทึกไฟล์เซฟ
save_downloaded=<@su>ดาวน์โหลดไฟล์เซฟไปที่ <@s>{path}</>
save_json_dialog=บันทึกข้อมูลเซฟเป็น json
load_from_documents=โหลดไฟล์เซฟจาก <@s>{path}</>
save_file_not_found=<@e>ไม่พบไฟล์เซฟ</>
save_file_found=<@su>กำลังโหลดเซฟจาก: <@t>{path}</></>

parse_save_error=<@e>เกิดข้อผิดพลาดขณะอ่านไฟล์เซฟของคุณ: {error}\n(เวอร์ชันโปรแกรม: <@s>{version}</>) (เวอร์ชันเกม: <@s>{game_version}</>) (รหัสประเทศ: <@s>{country_code}</>)\n{{report_message}}</>
load_json_fail=<@e>โหลดข้อมูลเซฟจาก json ไม่สำเร็จ ({error})</>
parse_json_fail=<@e>อ่านไฟล์ json ไม่สำเร็จ ไฟล์ของคุณเป็นรูปแบบ JSON จริงหรือไม่?</e>
editor_version_mismatch=<@w>เวอร์ชันโปรแกรมไม่ตรงกัน ไฟล์เซฟอาจใช้กับโปรแกรมนี้ไม่ได้ เวอร์ชัน Json: <@t>{json_version}</>, เวอร์ชันโปรแกรม: <@t>{editor_version}</></>
save_management=จัดการไฟล์เซฟ
save_save=บันทึกเซฟ
save_save_file=บันทึกเซฟไปยังไฟล์ที่กำหนด
save_save_documents=บันทึกเซฟไปที่ {path}
save_upload=อัปโหลดไฟล์เซฟไปยังเซิร์ฟเวอร์และรับรหัสถ่ายโอนกับรหัสยืนยัน
unban_account=ปลดแบนบัญชี / แก้ปัญหา Save Used Elsewhere

adb_push_rerun=ใช้ adb ส่งไฟล์เซฟไปยังอุปกรณ์ (รันเกมใหม่หลังส่งเสร็จ)
adb_push=ใช้ adb ส่งไฟล์เซฟไปยังอุปกรณ์ (ไม่รันเกมใหม่หลังส่งเสร็จ)
adb_push_success=<@su>ส่งไฟล์เซฟไปยังอุปกรณ์แล้ว</>
adb_push_fail=<@e>ส่งไฟล์เซฟไปยังอุปกรณ์ไม่สำเร็จ</> ({error})
adb_rerun_success=<@su>รันเกมใหม่สำเร็จแล้ว</>
adb_rerun_fail=<@e>รันเกมใหม่ไม่สำเร็จ</> ({error})

export_save=ส่งออกไฟล์เซฟเป็น json
save_success=<@su>บันทึกไฟล์เซฟไปที่ <@s>{path}</>
export_success=<@su>ส่งออกข้อมูลเซฟไปที่ <@s>{path}</>
init_save=รีเซ็ตไฟล์เซฟ
init_save_confirm=คุณแน่ใจหรือไม่ว่าต้องการรีเซ็ตไฟล์เซฟ? ({{y/n}}):
init_save_success=<@su>รีเซ็ตไฟล์เซฟสำเร็จแล้ว</>

adb_pulling=<@q>กำลังดึงไฟล์เซฟจากอุปกรณ์ด้วยชื่อแพ็กเกจ <@s>{package_name}</> ผ่าน adb ...</>
adb_pull_fail=<@e>ดึงไฟล์เซฟจากอุปกรณ์ด้วยชื่อแพ็กเกจ <@s>{package_name}</> ไม่สำเร็จ ({error}) ผ่าน adb

storage_pulling=<@q>กำลังดึงไฟล์เซฟจาก root storage ด้วยชื่อแพ็กเกจ <@s>{package_name}</>...</>
storage_pull_fail=<@e>ดึงไฟล์เซฟจาก root storage ด้วยชื่อแพ็กเกจ <@s>{package_name}</> ไม่สำเร็จ ({error})

not_rooted_error=<@e>อุปกรณ์นี้ดูเหมือนจะยังไม่ได้ root หรือโปรแกรมไม่ได้รันด้วยสิทธิ์ root</>

upload_items=อัปโหลดไอเทมที่จัดการไปยังเซิร์ฟเวอร์
upload_items_success=<@su>อัปโหลดไอเทมที่จัดการสำเร็จแล้ว</>
upload_items_fail=<@e>อัปโหลดไอเทมที่จัดการไม่สำเร็จ</>

load_save=โหลดไฟล์เซฟ
load_save_success=<@su>โหลดไฟล์เซฟสำเร็จแล้ว</>
account=บัญชี

save_before_exit=<@q>บันทึกการเปลี่ยนแปลงล่าสุดก่อนออกหรือไม่? (<@s>y</>/<@s>n</>):</>
save_temp_success=<@su>กู้คืนไฟล์เซฟจากไฟล์ temp สำเร็จแล้ว</>
save_temp_fail=<@e>กู้คืนไฟล์เซฟจากไฟล์ temp ไม่สำเร็จ การเปลี่ยนแปลงล่าสุดสูญหาย</> ({error})\n{traceback}
save_temp_not_found=<@e>กู้คืนไฟล์เซฟจากไฟล์ temp ไม่สำเร็จ การเปลี่ยนแปลงล่าสุดสูญหาย</> (ไม่พบไฟล์ temp)

cant_detect_cc=<@w>ไม่สามารถตรวจจับรหัสประเทศจากไฟล์เซฟได้ \nกรุณากรอกรหัสประเทศด้วยตนเอง</>
failed_to_load_save_gv=โหลดไฟล์เซฟสำเร็จแต่ค่าบางอย่างไม่เป็นไปตามที่คาดไว้ จึงหยุดการทำงานเพื่อป้องกันไฟล์เซฟเสียหาย
failed_to_load_save=โหลดไฟล์เซฟไม่สำเร็จ
failed_to_save_save=บันทึกไฟล์เซฟไม่สำเร็จ

game_version_dialog=กรอกเวอร์ชันเกม (เช่น <@t>12.2.1</>):
invalid_game_version=<@e>เวอร์ชันเกมไม่ถูกต้อง</>
country_code_set=<@su>ตั้งรหัสประเทศเป็น <@s>{cc}</> สำเร็จแล้ว
game_version_set=<@su>ตั้งเวอร์ชันเกมเป็น <@s>{version}</> สำเร็จแล้ว

convert_region=แปลงรหัสประเทศ (เช่น en -\> jp)
convert_version=แปลงเวอร์ชันเกม (เช่น 12.2.1 -\> 12.2.0)

cc_warning=<@w>คำเตือน: อาจทำให้เกิดปัญหากับไฟล์เซฟของคุณ อาจพบบั๊กหรือแอปขัดข้อง หากแจ้งบั๊ก กรุณาระบุด้วยว่าคุณใช้ฟีเจอร์นี้ คุณควรเข้าเมนูฐานแมว/อัปเกรดหลังใช้ฟีเจอร์นี้ เพื่อให้เกมทำการเปลี่ยนแปลงที่จำเป็นกับไฟล์เซฟของคุณ</>\nรหัสประเทศปัจจุบัน: <@t>{current}</>
gv_warning=<@w>คำเตือน: อาจทำให้เกิดปัญหากับไฟล์เซฟของคุณ อาจพบบั๊กหรือแอปขัดข้อง หากแจ้งบั๊ก กรุณาระบุด้วยว่าคุณใช้ฟีเจอร์นี้ คุณควรเข้าเมนูฐานแมว/อัปเกรดหลังใช้ฟีเจอร์นี้ เพื่อให้เกมทำการเปลี่ยนแปลงที่จำเป็นกับไฟล์เซฟของคุณ</>\nเวอร์ชันเกมปัจจุบัน: <@t>{current}</>

create_new_save_success=<@su>สร้างไฟล์เซฟใหม่สำเร็จแล้ว</>
create_new_save=สร้างไฟล์เซฟใหม่
create_new_save_warning=<@w>คำเตือน: ฟีเจอร์หลายอย่างของโปรแกรมจะใช้ไม่ได้กับไฟล์เซฟที่สร้างขึ้นอัตโนมัติ คุณต้องโหลดเข้าเกมก่อน แล้วค่อยโหลดกลับเข้าโปรแกรมอีกครั้ง\nอาจมีการเปลี่ยนแปลงในเวอร์ชันถัดไปของโปรแกรม</>

parse_ignored_error=<@w>คำเตือน: <@e>{error}<>\n<@w>ข้ามเนื่องจากตั้งค่าสถานะ Ignore Parse Error ไว้ อาจทำให้เกิดปัญหาได้!</> 

select_package_name=เลือกชื่อแพ็กเกจ:

adb_not_installed=
><@e>ยังไม่ได้เพิ่ม adb ลงในตัวแปรสภาพแวดล้อม PATH หรือที่อยู่ของ executable ไม่ถูกต้อง ลองแก้ไขที่อยู่ adb ในการตั้งค่า
>ค่าปัจจุบัน: <@s>{path}</>
>ข้อผิดพลาด: <@s>{error}</></>

waydroid_not_installed=<@e>ไม่ได้ติดตั้ง Waydroid หรือเกิดข้อผิดพลาด: {error}</>

root_push_not_android_error=<@e>Root push ใช้ได้เฉพาะบนอุปกรณ์ android เท่านั้น</>
root_push_success=<@su>เขียนไฟล์เซฟลง root storage สำเร็จแล้ว</>
root_push_fail=<@e>เขียนไฟล์เซฟลง root storage ไม่สำเร็จ ข้อผิดพลาด: <@s>{error}</></>

root_rerun_success=<@su>รันเกมใหม่สำเร็จแล้ว</>
root_rerun_fail=<@e>รันเกมใหม่ไม่สำเร็จ ข้อผิดพลาด: <@s>{error}</></>

root_push=ใช้ root ส่งไฟล์เซฟตรงเข้าเกม
root_push_rerun=ใช้ root ส่งไฟล์เซฟตรงเข้าเกม (และรันเกมใหม่)

select_recent=เลือกเซฟล่าสุด:
recent_save=<@s><@q>{inquiry_code}</> <@t>{cc}</>-<@t>{gv}</> @ <@t>{year}</>-<@t>{month}</>-<@t>{day}</> <@t>{hour}</>:<@t>{minute}</>:<@t>{second}</> - ที่อยู่เดิม: <@q>{name}</></>

load_recent_saves=โหลดจากเซฟล่าสุดและไฟล์สำรอง
no_recent_saves=<@w>ไม่มีเซฟล่าสุด</>
current_save=\nเซฟปัจจุบัน: <@t>{cc}</>-<@t>{gv}</> Inquiry: <@t>{inquiry_code}</>

root_storage_pull=ดึงไฟล์เซฟจาก root storage
