theme_text=
>ธีมปัจจุบัน: <@s>{theme_name}</> (เวอร์ชัน <@s>{theme_version}</>)
>สร้างโดย <@s>{theme_author}</>
>ตำแหน่งไฟล์ธีม: <@s>{theme_path}</>

default_theme_text=
>ธีมปัจจุบัน: <@s>ค่าเริ่มต้น</>
>ตำแหน่งไฟล์ธีม: <@s>{theme_path}</>

checking_for_theme_updates=กำลังตรวจสอบอัปเดตของธีมภายนอก <@t>{theme_name}</>...
external_theme_updated=<@su>อัปเดตธีมภายนอก <@t>{theme_name}</> เป็นเวอร์ชัน <@t>{version}<@t> สำเร็จแล้ว\n{{restart_to_see_changes}}</>
external_theme_no_update=<@su>ธีมภายนอก <@t>{theme_name}</> ไม่ต้องอัปเดต เวอร์ชันล่าสุดคือ <@t>{version}<@t></>
theme_changed=<@su>เปลี่ยนธีมเป็น <@t>{theme_name}</> สำเร็จแล้ว\n{{restart_to_see_changes}}</>
theme_removed=<@su>ลบธีม <@t>{theme_name}</> สำเร็จแล้ว\n{{restart_to_see_changes}}</>
no_external_themes=<@w>ไม่พบธีมภายนอก</>


theme_dialog=เลือกธีม:
add_theme=เพิ่มธีม
remove_theme=ลบธีม
theme_remove_dialog=เลือกธีมที่ต้องการลบ:
enter_theme_git_repo=กรอก git repository ของธีม (เช่น <@t>https://codeberg.org/fieryhenry/ExampleEditorTheme.git</>):
theme_already_exists=<@e>มีธีมชื่อ <@s>{theme_name}</> อยู่แล้ว</>\nต้องการเขียนทับหรือไม่? ({{y/n}}):
theme_added=<@su>เพิ่มธีมสำเร็จแล้ว</>
