local_version=<@q>เวอร์ชันในเครื่อง: <@s>{local_version}</></>
latest_version=<@q>เวอร์ชันล่าสุด: <@s>{latest_version}</></>

update_check_fail=<@e>ไม่สามารถตรวจสอบการอัปเดตได้ ลองตรวจสอบการเชื่อมต่ออินเทอร์เน็ตของคุณ</>

update_available=
><@q>มีอัปเดตใหม่: <@s>{latest_version}</>
>ต้องการอัปเดตหรือไม่? <@t>({{y/n}})</>:
update_success=
><@t>อัปเดตสำเร็จ
>กรุณารีสตาร์ทโปรแกรม</>
update_fail=
><@e>อัปเดตไม่สำเร็จ
>กรุณาอัปเดตด้วยตนเอง</>
>คำสั่ง: <@s>pip install --upgrade bcsfe</>

version_line={{local_version}} | {{latest_version}}

disable_update_message=ต้องการปิดข้อความแจ้งเตือนอัปเดตหรือไม่? <@t>({{y/n}}):</>
